### ISSUE TITLE
[Feature Request] YML config options

### ISSUE THREAD

**Issue by Sidefix** [peer-calls/peer-calls#149]
**Describe the feature**

Hello!

This is a great server and it works wonderfully during WFH when I need to perform some troubleshooting for family members, and I was wondering whether it would be possible to include configuration options in the YML for additional things such as:

   - Enable or Disable Encryption option
   - Enable or Disable File Sharing
   - Enable or Disable Automatic Camera Start
   - Enable or Disable a 'default' room
   - Enable or Disable creation of rooms
   - Enable or Disable showing of debug info (client version, network type, 'connected' info in the top right hand side etc)

All of these could reside within the YML as booleans that could be set to true or false at startup.

Thank you in advance for your considerations!

**Comment by jeremija** [comment]
Hi @Sidefix, I suppose something like this could be implemented, but I currently don't have the time for this.

I'd be happy to provide guidance if you wish to try to implement it yourself and submit a pull request.

**Comment by Sidefix** [comment]
Sure @jeremija I would give it a shot. Just let me know where the modifications need to be done and what tools I might need. I think I can manage from there.

**Comment by jeremija** [comment]
A few things would need to be updated. First we'd need to be able to read these values from `yaml` or environment variables.
 I recommend adding the `disabled` prefix to the boolean values so that the default behavior stays the same.

For example:

```yaml
ui:
  disable_insertable_streams: true # env var UI_DISABLE_INSERTABLE_STREAMS=true
  disable_file_sharing: true       # env var UI_DISABLE_FILE_SHARING
  rooms:                           # env var UI_ROOMS=room1,room2
    - room1
    - room2
  disable_console:                 # env var UI_DISABLE_CONSOLE=true
  default_room:   'default-room'   # env var UI_DEFAULT_ROOM=default-room
```

Could you clarify by the meaning of the default room setting? Do I understand correctly that predefined rooms would only allow certain rooms to be joined, and no other ones?

Then you'd need to modify the types and functions in `configtypes.go` and `configread.go` so these config values can be properly parsed. Then update the `mux.go` to actually render these values.

Nex you'd need to update the `window.ts` file to parse these new config values. I have actually been thinking about updating the logic in `window.ts` to read a single JSON value containing all config entries from a single instead of so many hidden input boxes.

Finally you'd need to update the UI to show/hide the desired functionality.

Note that the `Enable or Disable Automatic Camera Start` will probably be resolved by #122.
