### ISSUE TITLE
Need help with TURN configuration

### ISSUE THREAD

**Issue by usrndcom** [peer-calls/peer-calls#167]
Hello, I would truly appreciate any help in properly configuring peer-calls to work with COTURN deployed in a docker

Could someone share an example of the config for both COTURN and peer-calls, maybe one used for peercalls.com

I'm getting TURN related errors like one below:

```
[  pion:ice:warn] failed to resolve stun host: <SERVER URL>:3478: address<SERVER URL>: no suitable address found
[  pion:ice:warn] Failed to allocate on turn.Client <SERVER URL>:3478 all retransmissions for rGaX4GOr3OEHSdYq failed
[  pion:ice:warn] failed to set gatheringState to GatheringStateComplete: the agent is closed
[   pion:pc:warn] Failed to accept RTCP SessionSRTCP has been closed
```

Below is my Docker compose in case it helps describe the context
 
```
version: '2'
services:
  coturn:
    image: instrumentisto/coturn
    container_name: coturn    
    command: -n
    command: --log-file=stdout
    command: --external-ip='$(detect-external-ip)'
    command: --relay-ip='$(detect-external-ip)'
    command: --min-port=49160
    command: --max-port=49300
    command: --use-auth-secret
    command: --cli-password=<SOME PASS>
    command: --static-auth-secret=<SOME SECRET>
    command: --no-multicast-peers
    command: --no-cli
    command: --no-tlsv1
    command: --no-tlsv1_1
    command: --cert=/etc/ssl/certs/localhost.crt
    command: --pkey=/etc/ssl/private/localhost.key 
    restart: always
    volumes:
      - ./ssl/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./ssl/localhost.key:/etc/ssl/private/localhost.key

    ports:
      - "3478:3478"
      - "5349:5349"
      - "49160-49300:49160-49300/udp"
      
  peercall:
    image: peercalls/peercalls:latest
    container_name: peercall
    restart: always
    volumes:
      - ./ssl/localhost.crt:/usr/local/cert/localhost.crt
      - ./ssl/localhost.key:/usr/local/cert/localhost.key
   ports:
      - 3000:3000
    environment:
      - PEERCALLS_TLS_CERT=/usr/local/cert/localhost.crt
      - PEERCALLS_TLS_KEY=/usr/local/cert/localhost.key
      - PEERCALLS_NETWORK_TYPE=sfu
      - PEERCALLS_NETWORK_SFU_JITTER_BUFFER=true
      - PEERCALLS_NETWORK_SFU_PROTOCOLS=udp4,udp6,tcp4,tcp6
      - PEERCALLS_ICE_SERVER_URLS=stun:stun.l.google.com:19302,turn:<SERVER URL>:3478
      - PEERCALLS_ICE_SERVER_AUTH_TYPE=secret
      - PEERCALLS_ICE_SERVER_SECRET=<SOME SECRET>
```
