### ISSUE TITLE
socket disconnected coturn + peer-calls

### ISSUE THREAD

**Issue by gharsallahmoez** [peer-calls/peer-calls#194]
**Describe the bug**
I'm running peer-calls with coturn server in Docker. when I join a call I get this error in the peer-calls log
```
 [wss] [ws] Subscription error: failed to get reader: received close frame: status = StatusNoStatusRcvd and reason = ""
/src/server/wsclient.go:91: read
```
* this is my config.yml file 
```yml
base_url: ''
bind_host: '0.0.0.0'
bind_port: 3000
iceServers:
- urls:
  - 'turn:myCorurnServerIp:8443?transport=udp'
  auth_type: secret
  auth_secret:
    username: 'example'
    secret: 'password'
```
* and this my turnserver.conf file for coturn container
```sh
no-stun

listening-port=8443
tls-listening-port=5349

listening-ip=myCorurnServerIp
relay-ip=myCorurnServerIp

fingerprint
lt-cred-mech
realm=live.droussi.com

use-auth-secret
static-auth-secret=password

total-quota=100

bps-capacity=0

stale-nonce

log-file=/var/log/turnserver/turn.log
no-loopback-peers
no-multicast-peers
```
* I'm running peer-calls with this command
 ```sh
 docker run --rm -it -p 8080:3000 -v ${PWD}/peer-calls/config.yml:/my/config.yml peercalls/peercalls:latest -c /my/config.yml
```
* and running coturn with this command
```sh
docker run -d --network=host \
           -v ${PWD}/coturn/turnserver.conf:/my/coturn.conf \
           --name=coturn \
            instrumentisto/coturn -c /my/coturn.conf
```

PS : the same configuration works well with [Spreed WebRTC](https://github.com/strukturag/spreed-webrtc) by following [this tutorial](https://www.linuxbabe.com/docker/install-spreed-webrtc-server-docker-image)

any help please?
