### ISSUE TITLE
Invalid reference to ConfigMap name from Deployment in official examples

### ISSUE THREAD

**Issue by danielxvu** [peer-calls/peer-calls#260]
**Describe the bug**

Perhaps I'm missing something but using the example manifests right after a fresh clone seems to result in an error unless the `configMap` reference is set to `peercall` since the example ConfigMap is named such; visit the following files to see what I mean:

- https://github.com/peer-calls/peer-calls/blob/master/deploy/configmap.yaml#L4
- https://github.com/peer-calls/peer-calls/blob/master/deploy/deployment.yaml#L23

**Bug Report Checklist**

N/A since it's a Kubernetes manifest issue.

**Steps To Reproduce**

Use the following sample from the examples in your own manifest(s) when creating/updating a Kubernetes cluster.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: peercalls
---
apiVersion: apps/v1
kind: Deployment
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: peercalls-config
```

**Expected behavior**

The pods specified in the Deployment should report as running when using kubectl to inspect said pods. Instead, they are stuck on `ContainerCreating`.

**Additional context**

I did not use Kustomize in this process, rather running `kubectl apply -f configmap.yaml` by hand and such. Here's the full manifest (with some values stripped for privacy) I was using when I noticed the problem:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: peercalls
data:
  config.yaml: |
    base_url: ''
    ice_servers:
    - urls:
      - ""
      auth_type: secret
      auth_secret:
        username: ""
        secret: ""
    store:
      type: redis
      redis:
        host: ""
        port: 6379
        prefix: peercalls
    network:
      type: mesh
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: peercalls
---
apiVersion: v1
kind: Service
metadata:
  name: peercalls
  labels:
    app.kubernetes.io/name: peercalls
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: peercalls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peercalls
spec:
  progressDeadlineSeconds: 120
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: peercalls
  template:
    metadata:
      labels:
        app.kubernetes.io/name: peercalls
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: peercalls-config
      containers:
        - name: peercalls
          image: ghcr.io/peer-calls/peer-calls:latest
          imagePullPolicy: IfNotPresent
          command: ["peer-calls", "-c", "/etc/peercalls/config.yaml"]
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /probes/liveness
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /probes/health
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: config-volume
              mountPath: /etc/peercalls
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          lifecycle:
            preStop:
              exec:
                command:
                  - sleep
                  - "10"
      serviceAccountName: peercalls
      securityContext:
        fsGroup: 1000
```
